name: c2_coffee
description: "A new Flutter project for C2 Coffee."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Pick image from gallery/camera
  image_picker: ^1.2.0

  # International phone field with country flags
  intl_phone_field: ^3.2.0

  # Date formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  image: ^4.9.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/c2_logo_black.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Recoleta
      fonts:
        - asset: assets/fonts/Recoleta Alt Bold.otf

    - family: Afacad
      fonts:
        - asset: assets/fonts/Afacad-Regular.ttf
        - asset: assets/fonts/Afacad-Medium.ttf
          weight: 500
        - asset: assets/fonts/Afacad-SemiBold.ttf
          weight: 600